import '@/app/globals.css';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';
import ScrollTopButton from '@/components/ui/buttons/ScrollTopButton';

const inter = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  params: { locale },
  children,
}: {
  params: { locale: string };
  children: React.ReactNode;
}) {

  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        <ScrollTopButton />
        {children}
      </body>
    </html>
  );
}
