CREATE TABLE IF NOT EXISTS equipment_types (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
) TABLESPACE pg_default;

ALTER TABLE equipment_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Equipment Types are viewable by everyone"
ON equipment_types
FOR SELECT
TO anon, authenticated
USING (true);   