DROP TABLE IF EXISTS provider_devices CASCADE;

CREATE TABLE IF NOT EXISTS provider_equipment (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id SMALLINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  equipment_id SMALLINT REFERENCES equipment(id) ON DELETE CASCADE,
  equipment_type_id SMALLINT REFERENCES equipment_types(id) ON DELETE CASCADE,
  name TEXT,
  description TEXT,
  CHECK (
    (equipment_id IS NULL) <> (equipment_type_id IS NULL)
  )
) TABLESPACE pg_default;

ALTER TABLE provider_equipment ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Provider Equipment is viewable by everyone"
ON provider_equipment
FOR SELECT
TO anon, authenticated
USING (true);   