CREATE TABLE IF NOT EXISTS equipment (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_type_id SMALLINT NOT NULL REFERENCES equipment_types(id) ON DELETE CASCADE,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  CONSTRAINT equipment_equipment_type_id_brand_model_key 
    UNIQUE (equipment_type_id, brand, model)
  ) TABLESPACE pg_default;

ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Equipment is viewable by everyone"
ON equipment
FOR SELECT
TO anon, authenticated
USING (true);   