CREATE TABLE IF NOT EXISTS internet_packages (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_id SMALLINT NOT NULL REFERENCES technologies(id) ON DELETE CASCADE,
    provider_id SMALLINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    infrastructure_provider_id SMALLINT NOT NULL REFERENCES infrastructure_providers(id) ON DELETE SET NULL,
    download_speed SMALLINT NOT NULL,
    upload_speed SMALLINT NOT NULL,
    data SMALLINT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT internet_packages_technology_id_provider_id_infrastructure_provider_id_download_speed_upload_speed_data_key
        UNIQUE (technology_id, provider_id, infrastructure_provider_id, download_speed, upload_speed, data)
) TABLESPACE pg_default;

ALTER TABLE internet_packages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Internet Packages are viewable by everyone"
ON internet_packages
FOR SELECT
TO anon, authenticated
USING (true);
