CREATE TABLE IF NOT EXISTS infrastructure_providers (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    is_partner BOOLEAN NOT NULL DEFAULT false
) TABLESPACE pg_default;

ALTER TABLE infrastructure_providers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Infrastructure Providers are viewable by everyone"
ON infrastructure_providers
FOR SELECT
TO anon, authenticated
USING (true);   