
CREATE TABLE IF NOT EXISTS address_technologies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_ads_oid TEXT NOT NULL REFERENCES addresses(ads_oid) ON DELETE CASCADE,
    technology_id SMALLINT NOT NULL REFERENCES technologies(id) ON DELETE CASCADE,
    provider_id SMALLINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    infrastructure_provider_id SMALLINT NOT NULL REFERENCES infrastructure_providers(id) ON DELETE SET NULL,
    min_download_speed SMALLINT NOT NULL,
    max_download_speed SMALLINT NOT NULL,
    CONSTRAINT address_technologies_address_ads_oid_technology_id_provider_id_infrastructure_provider_id_min_download_speed_max_download_speed_key
        UNIQUE (address_ads_oid, technology_id, provider_id, infrastructure_provider_id, min_download_speed, max_download_speed)
) TABLESPACE pg_default;

ALTER TABLE address_technologies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Address Technologies are viewable by everyone"
ON address_technologies
FOR SELECT
TO anon, authenticated
USING (true);
