CREATE TABLE IF NOT EXISTS equipment_combinations (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT
) TABLESPACE pg_default;

ALTER TABLE equipment_combinations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Equipment Combinations is viewable by everyone"
ON equipment_combinations
FOR SELECT
TO anon, authenticated
USING (true);   