CREATE TABLE IF NOT EXISTS discount_campaigns (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT,
  name TEXT,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE
) TABLESPACE pg_default;

ALTER TABLE discount_campaigns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Discount Campaigns is viewable by everyone" ON discount_campaigns FOR
SELECT
  TO anon,
  authenticated USING (true);
